
import { ChatState, ITool } from 'chat-list/types/plugin';
import api from "@api/index";
import { ImageSearchResult } from 'chat-list/types/search';
import { buildChatMessage } from 'chat-list/utils';

export const func = async ({ input, num = 5, context }: { input: string, num: number, context: ChatState }) => {
    const { appendMsg } = context;
    const results = await api.searchImages({
        keyword: input,
        num
    }) as ImageSearchResult[];

    const targets = results.filter(p => p.imageUrl);
    if (targets.length == 0) {
        return 'Search result is empty'
    }
    const content = results.map(({ title, imageUrl }) => {
        return `![${title}](${imageUrl})`;
    }).join('\n\n');

    const msg = buildChatMessage(content, 'text', 'assistant');
    appendMsg(msg);

    // const images = results.map(({ title, imageUrl }) => {
    //     return { title, imageUrl };
    // });

    // return JSON.stringify(images, null, 2);
    return `The pictures has been shown to the user. You don't have to return it, Tell the user to select the picture aboved to insert into the document.`
}

export default {
    type: 'function',
    name: 'search_images',
    description: "Search images by Google",
    parameters: {
        "type": "object",
        "properties": {
            "input": {
                "type": "string",
                "description": `keywords, generated by context.`
            },
            "num": {
                "type": "number",
                "description": `Image number,default is 5`
            },
        },
        "required": ['input']
    },
    func
} as unknown as ITool;

