// export interface ImageCreateRequest {
//     agent?: string;
//     model: 'dall-e-3';
//     prompt: string;
//     n?: number;
//     size?: ImageSize;
//     style?: 'vivid' | 'natural';
//     quality?: ImageGenerationQuality;
// }

/** Represents the request data used to generate images. */
export declare interface IGetImagesOptions {
    /**
     * The model to use for image generation.
     */
    model: 'dall-e-3';
    /**
     * The prompt to guide the image generation.
     */
    prompt: string;
    /**
     * The number of images to generate.
     * Dall-e-3 models only support a value of 1.
     */
    n?: number;
    /**
     * The desired dimensions for generated images.
     * Dall-e-3 models support 1024x1024, 1792x1024, or 1024x1792.
     */
    size?: ImageSize;
    /** The format in which image generation response items should be presented. */
    response_format?: ImageGenerationResponseFormat;
    /**
     * The desired image generation quality level to use.
     */
    quality?: ImageGenerationQuality;
    /**
     * The desired image generation style to use.
     */
    style?: ImageGenerationStyle;
    /** A unique identifier representing your end-user, which can help to monitor and detect abuse. */
    user?: string;
}

/**
 * A representation of a single generated image, provided as either base64-encoded data or as a URL from which the image
 * may be retrieved.
 */
export declare interface ImageGenerationData {
    /** The URL that provides temporary access to download the generated image. */
    url?: string;
    /** The complete data for an image, represented as a base64-encoded string. */
    b64_json?: string;
    /**
     * The final prompt used by the model to generate the image.
     * Only provided with dall-3-models and only when revisions were made to the prompt.
     */
    revised_prompt?: string;
}

/**
 * An image generation configuration that specifies how the model should prioritize quality, cost, and speed.
 * Only configurable with dall-e-3 models.
 */
/** "standard", "hd" */
export declare type ImageGenerationQuality = "standard" | "hd";

/** The format in which the generated images are returned. */
/** "url", "b64_json" */
export declare type ImageGenerationResponseFormat = "url" | "b64_json";

/** The result of a successful image generation operation. */
export declare interface ImageGenerations {
    /**
     * A timestamp representing when this operation was started.
     * Expressed in seconds since the Unix epoch of 1970-01-01T00:00:00+0000.
     */
    created: Date;
    /** The images generated by the operation. */
    data: ImageGenerationData[];
}

/**
 * An image generation configuration that specifies how the model should incorporate realism and other visual characteristics.
 * Only configurable with dall-e-3 models.
 */
/** "natural", "vivid" */
export declare type ImageGenerationStyle = "natural" | "vivid";

/** The desired size of generated images. */
/** "1024x1024", "1792x1024", "1024x1792" */
export declare type ImageSize = "1024x1024" | "1792x1024" | "1024x1792";
