
import sheet from '@api/sheet';
// import second from 'tes'
import instruction from './instruction.md';
import { ITool } from 'chat-list/types/plugin';
import { arrayToMarkdownTable, getFunc } from 'chat-list/utils';
import { getValues } from 'chat-list/service/sheet';

export const main = async ({ script, table_name }: { script: string, table_name?: string }) => {
    const data = await getValues();
    const fun = getFunc(script);
    const funResult = fun(data);
    const name = table_name || ('sheet' + (Math.random() * 100).toFixed(0));
    await sheet.initSheet(name, [], { active: false });
    await sheet.setValues(funResult, name);
    const result = arrayToMarkdownTable(funResult);
    return result;
};

export default {
    name: 'create-by-condition',
    description: instruction,
    parameters: {
        "type": "object",
        "properties": {
            "script": {
                "type": "string",
                "description": `The code with function name:main  `
            },
            "table_name": {
                "type": "string",
                "description": `The table name generated by user requirements`
            }
        },
        "required": ['script']
    },
    func: main
} as unknown as ITool;